platform: linux


image_resource:
  type: registry-image
  source:
    repository: cloudfoundry/cf-deployment-concourse-tasks

inputs:
  - name: capi-ci
  - name: capi-ci-private

outputs:
  - name: environment

run:
  path: capi-ci/ci/bbl-tasks/extract_bbl_environment.sh

params:
  ENV_NAME: ""
  DEPLOYMENT_NAME: cf
